### ISSUE TITLE
Stop all UILevels from preloading (huge performance eater)

### ISSUE THREAD

**Issue by flo-wolf** [Badeye/Flip-Fall#57]

**Comment by MeikelLP** [comment]
Where was it fixed? Please add a commit hash.

**Comment by flo-wolf** [comment]
https://github.com/Badeye/Impulse/blob/a36c1b49f8ddf7222c9bc5d361bdd65a70fc3498/Assets/Resources/Scripts/UI/Levelselection/UILevelPlacer.cs

**Comment by MeikelLP** [comment]
Thx
