### ISSUE TITLE
UI scaling only works flawless on 1920x1080 - other resulutions scale badly.

### ISSUE THREAD

**Issue by flo-wolf** [Badeye/Flip-Fall#78]
https://play.google.com/apps/publish/?hl=en&dev_acc=11169658135501759044#PreLaunchReportPlace:p=com.florianwolf.flipfall

**Comment by MeikelLP** [comment]
```
403. That’s an error.

We're sorry, but you do not have access to this page. That’s all we know.
```

Not accessible for other people.

**Comment by flo-wolf** [comment]
Wasn't meant to be accessible for others, just a quick note to my self.
Google ran my app on different test devices while creating screenshots, videos, logs and errors for me to review. That way I am able to check the performance on other devices without owning them or using an emulator. Kinda cool, revealed fucked up UI scaling and positioning on anything that is not 16:9.

**Comment by MeikelLP** [comment]
If it's only for you don't put your notes on a public issue.

**Comment by flo-wolf** [comment]
Where else to put it, this is convenient. Snce I am the only one developing I don't see this as an issue.

**Comment by MeikelLP** [comment]
But Github isn't a note database. Use Google Drive / Dropbox or whatever

**Comment by flo-wolf** [comment]
Nah I'll make use of it how I please.
